-- OMI Gateway Database Schema (Supabase / PostgreSQL)

-- 1. USERS TABLE
-- Stores paying customers.
create table public.users (
  id uuid default gen_random_uuid() primary key,
  email text unique not null,
  api_key text unique not null,
  plan_tier text default 'pro' check (plan_tier in ('hobby', 'pro', 'enterprise')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  is_active boolean default true
);

-- 2. REQUEST LOGS
-- Stores usage data for analytics (The "Tinybird" replacement for MVP).
-- NOTE: We do NOT store the raw prompt/response text for privacy.
create table public.request_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.users(id),
  mode_used text not null,
  model_routed_to text not null,
  tokens_input int default 0,
  tokens_output int default 0,
  latency_ms int,
  status_code int default 200,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. SECURITY & INDEXES
-- Enable Row Level Security (RLS)
alter table public.users enable row level security;
alter table public.request_logs enable row level security;

-- Create indexes for fast dashboard queries
create index idx_logs_user_id on public.request_logs(user_id);
create index idx_logs_timestamp on public.request_logs(timestamp desc);
create index idx_users_api_key on public.users(api_key);

-- 4. HELPER: Function to validate API Key (called by n8n or middleware)
create or replace function verify_key(input_key text)
returns table (user_id uuid, plan text) as $$
begin
  return query
  select id, plan_tier
  from public.users
  where api_key = input_key
  and is_active = true;
end;
$$ language plpgsql security definer;
