import os
import sys
import json
import shutil
import asyncio

# Ensure project root is in path
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.append(project_root)

from services.automation_engine import AutomationEngine

async def main():
    print("====================================================")
    print("Starting OMI Economic Intelligence Loop Verification")
    print("====================================================")
    
    # 1. Clear memory cache files to ensure a clean run
    memory_dir = os.path.join(project_root, "memory")
    reports_dir = os.path.join(project_root, "docs", "reports")
    
    cached_agents = [
        "ModelIntelligenceAgent",
        "PricingAgent",
        "BenchmarkAgent",
        "RouterEvolutionAgent",
        "CompetitiveIntelligenceAgent",
        "GrantAgent",
        "ReadmeEvolutionAgent",
        "LearningIntelligenceAgent",
        "ProofToGrowthAgent",
        "EcosystemIntelligenceAgent",
        "ConversionIntelligenceAgent",
        "TransparencyIntelligenceAgent"
    ]
    
    print("\n--- Cleaning up existing cache files for 100% clean baseline ---")
    files_to_delete = [
        "benchmark_memory.json",
        "pricing_memory.json",
        "model_memory.json",
        "grant_memory.json",
        "growth_memory.json",
        "growth_agent_memory.json",
        "ecosystem_memory.json",
        "conversion_memory.json",
        "transparency_memory.json",
        "engineering_memory.json",
        "learning_memory.json",
        "routing_memory.json",
        "pilot_memory.json",
        "calibration_memory.json",
        "provider_memory.json"
    ]
    for filename in files_to_delete:
        filepath = os.path.join(memory_dir, filename)
        if os.path.exists(filepath):
            try:
                os.remove(filepath)
                print(f"Removed memory file: {filename}")
            except Exception as e:
                print(f"Failed to remove {filename}: {e}")
                
    # Also clean JSON report files
    json_reports = [
        "model_intelligence_data.json",
        "pricing_data.json",
        "router_evolution_data.json",
        "competitive_data.json",
        "grant_data.json",
        "readme_recommendations.json",
        "agent_scorecard_data.json",
        "learned_patterns.json",
        "growth_data.json",
        "growth_report.md",
        "ecosystem_data.json",
        "ecosystem_report.md",
        "conversion_data.json",
        "pilot_conversion_report.md",
        "transparency_data.json",
        "transparency_report.md"
    ]
    for filename in json_reports:
        filepath = os.path.join(reports_dir, filename)
        if os.path.exists(filepath):
            try:
                os.remove(filepath)
                print(f"Removed report file: {filename}")
            except Exception as e:
                print(f"Failed to remove {filename}: {e}")
                
    # Benchmark results JSON
    bench_json = os.path.join(project_root, "benchmarks", "live", "benchmark_results.json")
    if os.path.exists(bench_json):
        try:
            os.remove(bench_json)
            print("Removed benchmarks/live/benchmark_results.json")
        except Exception as e:
            print(f"Failed to remove benchmark results: {e}")

    # Knowledge Base dossiers
    kb_files = ["distilled_routing.md", "provider_reputation.md"]
    for filename in kb_files:
        filepath = os.path.join(project_root, "docs", "knowledge_base", filename)
        if os.path.exists(filepath):
            try:
                os.remove(filepath)
                print(f"Removed knowledge base file: {filename}")
            except Exception as e:
                print(f"Failed to remove knowledge base file {filename}: {e}")

    # Clean up public assets generated by ProofToGrowthAgent, EcosystemIntelligenceAgent, ConversionIntelligenceAgent, and TransparencyIntelligenceAgent
    public_dir = os.path.join(project_root, "docs", "public")
    public_files = [
        "weekly_public_benchmark_leaderboard.md",
        "weekly_economic_savings_report.md",
        "weekly_release_notes.md",
        "pilot_onboarding_pack.md",
        "indiaai_grant_submission_brief.md",
        "community_health_report.md",
        "contributor_leaderboard.md",
        "evidence_wall.md",
        "weekly_project_digest.md",
        "monthly_model_report.md",
        "calibration_report.md",
        "economic_efficiency_report.md",
        "sovereign_report.md",
        "benchmark_results.csv",
        "provider_rankings.csv",
        "calibration_metrics.csv",
        "reproducibility_package.md",
        "methodology_docs.md",
        "benchmark_specifications.md"
    ]
    for filename in public_files:
        filepath = os.path.join(public_dir, filename)
        if os.path.exists(filepath):
            try:
                os.remove(filepath)
                print(f"Removed public asset: {filename}")
            except Exception as e:
                print(f"Failed to remove public asset {filename}: {e}")

    engine = AutomationEngine.get_instance()
    
    # 2. RUN 1: Fresh execution (No Cache Hits)
    print("\n--- Cycle 1: Fresh Run (Populating Cache) ---")
    await engine.run_daily_telemetry_check()
    await engine.run_weekly_benchmark_cycle()
    
    scorecard_path = os.path.join(reports_dir, "agent_scorecard_data.json")
    if not os.path.exists(scorecard_path):
        print("[ERROR] agent_scorecard_data.json was not generated after Cycle 1.")
        sys.exit(1)
        
    with open(scorecard_path, "r", encoding="utf-8") as f:
        data1 = json.load(f)
        
    print("\nCycle 1 Cache Hit Statuses (should all be false):")
    for a in data1.get("audit", []):
        name = a["agent_name"]
        if name in cached_agents:
            print(f"  - {name}: Cache Hit = {a['cache_hit']}")
            if a["cache_hit"] is not False:
                print(f"[WARNING] {name} expected cache_hit to be False on first run, got {a['cache_hit']}")

    # 3. RUN 2: Immediate execution (100% Cache Hits for Cached Agents)
    print("\n--- Cycle 2: Immediate Run (Enforcing Caching & Early Termination) ---")
    await engine.run_daily_telemetry_check()
    await engine.run_weekly_benchmark_cycle()
    
    if not os.path.exists(scorecard_path):
        print("[ERROR] agent_scorecard_data.json was not generated after Cycle 2.")
        sys.exit(1)
        
    with open(scorecard_path, "r", encoding="utf-8") as f:
        data2 = json.load(f)
        
    print("\nCycle 2 Cache Hit Statuses (must all be true):")
    all_hits = True
    found_agents = []
    for a in data2.get("audit", []):
        name = a["agent_name"]
        if name in cached_agents:
            found_agents.append(name)
            print(f"  - {name}: Cache Hit = {a['cache_hit']}")
            if not a["cache_hit"]:
                print(f"[ERROR] {name} failed to trigger cache hit on second run!")
                all_hits = False

    # Check that we verified all 7 cached agents
    missing_agents = set(cached_agents) - set(found_agents)
    if missing_agents:
        print(f"[ERROR] Some cached agents were missing from scorecard: {missing_agents}")
        all_hits = False
        
    print("\n====================================================")
    if all_hits:
        print("[VERIFICATION PASSED] 100% of cached agents triggered a memory hit and terminated early!")
        sys.exit(0)
    else:
        print("[VERIFICATION FAILED] One or more cached agents did not trigger early termination.")
        sys.exit(1)

if __name__ == "__main__":
    asyncio.run(main())
